### ISSUE TITLE
Custom Nbt-value for an entity (player)

### ISSUE THREAD

**Issue by LeoStoch** [ShaneBeee/Sk-NBeeT#14]
Hey, I think that is probably a bug: 
Server version is final 1.13.2
SK-NBeeT is 2.4.1

I am trying to add some custom nbt to myself (player) but when I am doing this (add "{test:""none""}" to entity-nbt of player) I am always getting teleported to the initialized world wit coordinated 0,0,0
and the nbt-values are not set.

**Comment by ShaneBeee** [comment]
This issue was already fixed a few versions ago.
Update your Sk-NBeeT, you are 6 versions behind.

**Comment by LeoStoch** [comment]
Updated to the newest version (2.7.2) and I am still having the same issue.

**Comment by ShaneBeee** [comment]
My apologies, it was actually the get NBT from a player that I fixed, and that fix I forgot to pass over to the add nbt as well.
Working on a fix right now!

**Comment by LeoStoch** [comment]
Okay, thanks. When do you estimate will there be a fixed version downloadable?

**Comment by ShaneBeee** [comment]
Hopefully soon. I got the version working, Im able to add things to the Player's NBT such as the amount of air they have left, but I'm not able to add custom tags. 
I think someone told me once you cant add custom tags to the NBT of an entity/Player.
Looking thru the NMS code, when you add NBT to an entity, its broken up into the sections of the NBT and those sections are saved. If the section does not exist it obviously won't save, since the NBT string itself is not applied to the entity, rather the bits are.

How accurate all of this is, I'm unsure.

**Comment by LeoStoch** [comment]
Well, someone sent me once this: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/persistence/PersistentDataContainer.java

and meatn it would help me storing data for a player...maybe it helps you^^

**Comment by ShaneBeee** [comment]
Thats a different thing to a degree.

After reading some posts on SpigotMC, it appears custom tags can be added to ItemStacks but not entities. So as of right now the current fix I have is this:
- NBT can be changed on an entity (anything that is current part of their NBT can be updated)
- Custom NBT can not be added

**Comment by LeoStoch** [comment]
Well, then do I have to overthink my plans. But anyway...I think this is still a bug (because a player is being teleported if it is being tried)^^

**Comment by ShaneBeee** [comment]
> But anyway...I think this is still a bug (because a player is being teleported if it is being tried)^^

That is fixed in the code I have written, I just haven't pushed anything yet.

**Comment by ShaneBeee** [comment]
Okay update has been pushed, fixed in [**2.7.1**](https://github.com/ShaneBeee/Sk-NBeeT/releases/tag/2.7.1)
